<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="7" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-06T20:31:23 IST" name="All Test Suite" finished-at="2025-03-06T20:31:23 IST" duration-ms="383">
    <groups>
      <group name="smoke">
        <method signature="PriorityExe.testCaseP()[pri:-7, instance:TestNg.PriorityExe@31c88ec8]" name="testCaseP" class="TestNg.PriorityExe"/>
        <method signature="PriorityExe.testCaseO()[pri:1, instance:TestNg.PriorityExe@31c88ec8]" name="testCaseO" class="TestNg.PriorityExe"/>
        <method signature="PriorityExe.testCaseD()[pri:4, instance:TestNg.PriorityExe@31c88ec8]" name="testCaseD" class="TestNg.PriorityExe"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-03-06T20:31:23 IST" name="C:/Users/Arpita/IdeaProjects/Maven_Edso/src/main/java" finished-at="2025-03-06T20:31:23 IST" duration-ms="383">
      <class name="TestNg.PriorityExe">
        <test-method signature="testCaseP()[pri:-7, instance:TestNg.PriorityExe@31c88ec8]" started-at="2025-03-06T20:31:23 IST" name="testCaseP" finished-at="2025-03-06T20:31:23 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseP -->
        <test-method signature="testCaseO()[pri:1, instance:TestNg.PriorityExe@31c88ec8]" started-at="2025-03-06T20:31:23 IST" name="testCaseO" finished-at="2025-03-06T20:31:23 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseO -->
        <test-method signature="testCaseL()[pri:2, instance:TestNg.PriorityExe@31c88ec8]" started-at="2025-03-06T20:31:23 IST" name="testCaseL" finished-at="2025-03-06T20:31:23 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseL -->
        <test-method signature="testCaseD()[pri:4, instance:TestNg.PriorityExe@31c88ec8]" started-at="2025-03-06T20:31:23 IST" name="testCaseD" finished-at="2025-03-06T20:31:23 IST" duration-ms="44" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestNg.PriorityExe.testCaseD(PriorityExe.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:151)
at org.testng.internal.thread.graph.TestNGFutureTask.<init>(TestNGFutureTask.java:15)
at org.testng.internal.thread.graph.GraphOrchestrator.runNodes(GraphOrchestrator.java:58)
at org.testng.internal.thread.graph.GraphOrchestrator.run(GraphOrchestrator.java:46)
at org.testng.TestTaskExecutor.execute(TestTaskExecutor.java:69)
at org.testng.TestRunner.privateRun(TestRunner.java:722)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseD -->
        <test-method signature="testCaseN()[pri:3, instance:TestNg.PriorityExe@31c88ec8]" started-at="2025-03-06T20:31:23 IST" name="testCaseN" finished-at="2025-03-06T20:31:23 IST" duration-ms="44" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestNg.PriorityExe.testCaseN(PriorityExe.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:151)
at org.testng.internal.thread.graph.TestNGFutureTask.<init>(TestNGFutureTask.java:15)
at org.testng.internal.thread.graph.GraphOrchestrator.runNodes(GraphOrchestrator.java:58)
at org.testng.internal.thread.graph.GraphOrchestrator.run(GraphOrchestrator.java:46)
at org.testng.TestTaskExecutor.execute(TestTaskExecutor.java:69)
at org.testng.TestRunner.privateRun(TestRunner.java:722)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseN -->
        <test-method signature="testCaseA()[pri:6, instance:TestNg.PriorityExe@31c88ec8]" started-at="2025-03-06T20:31:23 IST" name="testCaseA" finished-at="2025-03-06T20:31:23 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseA -->
      </class> <!-- TestNg.PriorityExe -->
    </test> <!-- C:/Users/Arpita/IdeaProjects/Maven_Edso/src/main/java -->
  </suite> <!-- All Test Suite -->
</testng-results>
